version: '3'

services: 

  limesurvey_system:
    container_name: limesurvey_system
    build:
        context: ./limesurvey
        dockerfile: Dockerfile
    depends_on:
        - db_system
    environment:
      MYSQL_HOST: db_system
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: mynewpassword
      MYSQL_DB: limesurvey
    ports:
        - 9090:80
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: consttier.tech:24224
        tag: limesurvey.access

  monit_system:
    container_name: monit_system
    build:
      context: ./monit
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2813:2812"
  
  db_system:
    container_name: db_system
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: mynewpassword
        MYSQL_DATABASE: limesurvey
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
        - "9907:3306"

  adminer_system:
    container_name: adminer_system
    image: adminer
    ports:
      - '8889:8080'


  fluentd:
    container_name: fluentd
    build: ./fluentd
    links: # Sends incoming logs to the elasticsearch container.
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: # Exposes the port 24224 on both TCP and UDP protocol for log aggregation
      - 24224:24224
      - 24224:24224/udp


  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.1
    expose: # Exposes the default port 9200
      - 9200
    environment:
      - discovery.type=single-node # Runs as a single-node
    volumes: # Stores elasticsearch data locally on the esdata Docker volume
      - esdata:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:8.7.1
    links: # Links kibana service to the elasticsearch container
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: # Runs kibana service on default port 5601
      - 5601:5601
    environment: # Defined host configuration
      - ELASTICSEARCH_HOSTS=http://consttier.tech:9200

  

volumes:
  mysql_data: 
  esdata:

networks:
  default:
    external:
      name: my_network